import { DM_Serif_Text, Mona_Sans } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";

//Google Fonts
const dmSerif = DM_Serif_Text({
  variable: "--font-serif",
  subsets: ["latin"], weight: '400',
});

const monaSans = Mona_Sans  ({
    variable: "--font-sans",
    subsets: ["latin"],
});

//Local Fonts
const modernNegra = localFont({
    src: "./fonts/ModernNegraDemo.ttf",
    variable: "--font-modern-negra",
    display: "swap"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${modernNegra.variable} ${monaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
